# Generated by Django 6.0.6 on 2026-06-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="quality",
            field=models.CharField(default="1080p", max_length=20),
        ),
    ]
