# Generated by Django 6.0.6 on 2026-06-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_generationjob_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
