# Generated by Django 6.0.6 on 2026-06-26 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_avatar_preview_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoDub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_video", models.FileField(upload_to="dubs/source/")),
                ("target_language", models.CharField(max_length=50)),
                (
                    "reference_audio",
                    models.FileField(
                        blank=True, null=True, upload_to="dubs/reference_audio/"
                    ),
                ),
                (
                    "output_video_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("extracting_audio", "Extracting Audio"),
                            ("translating", "Translating & Dubbing"),
                            ("lip_syncing", "Lip Syncing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_dubs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voice_clone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_dubs",
                        to="api.voiceclone",
                    ),
                ),
            ],
        ),
    ]
