# Generated by Django 6.0.6 on 2026-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_videodub"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="training_data",
            field=models.FileField(
                blank=True, null=True, upload_to="avatars/training/"
            ),
        ),
    ]
