# Generated by Django 6.0.6 on 2026-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_avatar_training_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="avatar",
            name="aspect_ratio",
            field=models.CharField(
                choices=[
                    ("16:9", "16:9 (Landscape)"),
                    ("9:16", "9:16 (Portrait)"),
                    ("1:1", "1:1 (Square)"),
                ],
                default="16:9",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="voiceclone",
            name="age_bracket",
            field=models.CharField(
                default="adult",
                help_text="e.g. 'young', 'adult', 'middle-aged'",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="voiceclone",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("neutral", "Neutral"),
                ],
                default="neutral",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="voiceclone",
            name="preview_audio",
            field=models.FileField(blank=True, null=True, upload_to="voice_previews/"),
        ),
    ]
